"""Regenerate docs/dashboard.md — the public project dashboard — and the
README's test badge, which is the same measurement on a second surface.

Numbers come from three places: the repository itself (version, test count,
source size, commit activity), PyPI and pypistats (downloads), and the GitHub
API (stars, forks, issues, latest release). Nothing is fetched at page-render
time, so the site stays a static build with no runtime service and no API key.

    py -3 tools/gen_metrics.py            # rewrite docs/dashboard.md + the badge
    py -3 tools/gen_metrics.py --offline  # repo-only numbers, no network

A failed fetch is an error, not a dash: writing placeholders over good data
would quietly turn the dashboard into a page of em-dashes that still looks like
it built correctly.
"""

import json
import os
import re
import subprocess
import sys
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'docs', 'dashboard.md')
README = os.path.join(ROOT, 'README.md')
REPO = 'babarmuhammad/claudectl'
PKG = 'claudectl'
UA = {'User-Agent': 'claudectl-docs-metrics'}

HEADER = """---
title: claudectl project dashboard
description: >-
  Live-ish numbers for claudectl — release version, PyPI downloads, GitHub stars, test
  count, source size and commit activity. Regenerated from PyPI and the GitHub API.
---

# Project dashboard

Generated by `tools/gen_metrics.py` from PyPI, the GitHub API and the repository
itself — do not edit by hand. Refreshed weekly by `.github/workflows/metrics.yml`.

"""


def _get(url, tries=3):
    """GET JSON, retrying a rate-limit or a server hiccup.

    pypistats answers 429 freely and the GitHub API throttles unauthenticated
    callers, so one bad second must not be the reason a weekly refresh writes
    em-dashes over real numbers."""
    for attempt in range(tries):
        try:
            req = urllib.request.Request(url, headers=UA)
            with urllib.request.urlopen(req, timeout=20) as r:
                return json.load(r)
        except urllib.error.HTTPError as e:
            if e.code not in (429, 500, 502, 503, 504) or attempt == tries - 1:
                raise
        except urllib.error.URLError:
            if attempt == tries - 1:
                raise
        time.sleep(5 * (attempt + 1))


def _git(*args):
    r = subprocess.run(('git',) + args, cwd=ROOT, capture_output=True, text=True,
                       encoding='utf-8', errors='ignore', timeout=60)
    return r.stdout.strip() if r.returncode == 0 else ''


def _n(v):
    """1234 -> '1,234'. None stays an em-dash so a missing source is visible."""
    return '—' if v is None else '{:,}'.format(v)


def _day(stamp):
    """ISO-8601 from either API, or a git date, down to the day."""
    if not stamp:
        return '—'
    return stamp[:10]


def repo_facts():
    version = re.search(r'^version\s*=\s*"([^"]+)"', _read('pyproject.toml'), re.M).group(1)
    py, loc, tests = 0, 0, 0
    # Named source roots, not a walk of the whole tree: a walk also counts a
    # scratch venv, a built wheel unpacked for a packaging test and anything
    # else sitting in the working copy, which is how this first reported 456
    # Python files for a 183-file project.
    for rel in ('claude_sessions', 'tools', 'tests', '.'):
        base = os.path.join(ROOT, rel)
        for dirpath, dirs, files in os.walk(base):
            dirs[:] = [] if rel == '.' else [d for d in dirs if d != '__pycache__']
            for name in files:
                if not name.endswith('.py'):
                    continue
                py += 1
                text = _read(os.path.join(dirpath, name), abs_ok=True)
                loc += len(text.splitlines())
                if name.startswith('test_'):
                    tests += len(re.findall(r'^\s*def test_', text, re.M))
    return {
        'version': version,
        'py_files': py,
        'loc': loc,
        'tests': tests,
        'docs_pages': len([f for f in os.listdir(os.path.join(ROOT, 'docs'))
                           if f.endswith('.md')]),
        'commits': int(_git('rev-list', '--count', 'HEAD') or 0),
        'commits_30d': int(_git('rev-list', '--count', '--since=30 days ago', 'HEAD') or 0),
        'last_commit': _day(_git('log', '-1', '--format=%cI')),
    }


def _read(rel, abs_ok=False):
    path = rel if abs_ok else os.path.join(ROOT, rel)
    with open(path, encoding='utf-8', errors='ignore') as f:
        return f.read()


def remote_facts():
    gh = _get('https://api.github.com/repos/%s' % REPO)
    out = {
        'stars': gh.get('stargazers_count'),
        'forks': gh.get('forks_count'),
        'issues': gh.get('open_issues_count'),
        'pushed': _day(gh.get('pushed_at')),
        'created': _day(gh.get('created_at')),
    }
    # A project can be on GitHub before it is on PyPI; 404 there is a fact, not
    # a failure, so it is the one fetch allowed to come back empty.
    try:
        pypi = _get('https://pypi.org/pypi/%s/json' % PKG)
        out['pypi_version'] = pypi['info']['version']
        out['releases'] = len(pypi.get('releases') or {})
        files = pypi.get('urls') or []
        out['released'] = _day(files[0]['upload_time_iso_8601']) if files else '—'
    except urllib.error.HTTPError as e:
        if e.code != 404:
            raise
        out.update(pypi_version=None, releases=None, released='—')
    try:
        recent = _get('https://pypistats.org/api/packages/%s/recent' % PKG)['data']
        out.update(dl_day=recent['last_day'], dl_week=recent['last_week'],
                   dl_month=recent['last_month'])
    except urllib.error.HTTPError as e:
        if e.code != 404:
            raise
        out.update(dl_day=None, dl_week=None, dl_month=None)
    return out


def render(r, x):
    now = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    p = [HEADER]
    p.append('## Release\n')
    p.append('| | |')
    p.append('|---|---|')
    p.append('| Version in this repository | **%s** |' % r['version'])
    p.append('| Published on PyPI | %s |' % (x.get('pypi_version') or 'not yet published'))
    p.append('| Latest upload | %s |' % x.get('released', '—'))
    p.append('| Releases to date | %s |' % _n(x.get('releases')))
    p.append('| License | MIT |')
    p.append('| Runtime dependencies | **0** |')
    p.append('')
    # Absolute, because both pages live on the apex marketing site — a relative
    # link would name a docs page that does not exist and fail --strict.
    p.append('[Download](https://claudectl.space/download/) · '
             '[Changelog](https://claudectl.space/changelog/)\n')

    p.append('## Downloads\n')
    p.append('From [pypistats.org](https://pypistats.org/packages/%s), mirrors excluded.\n' % PKG)
    p.append('| Last day | Last week | Last month |')
    p.append('|---|---|---|')
    p.append('| %s | %s | %s |'
             % (_n(x.get('dl_day')), _n(x.get('dl_week')), _n(x.get('dl_month'))))
    p.append('')

    p.append('## Repository\n')
    p.append('| | |')
    p.append('|---|---|')
    p.append('| Stars | %s |' % _n(x.get('stars')))
    p.append('| Forks | %s |' % _n(x.get('forks')))
    p.append('| Open issues and pull requests | %s |' % _n(x.get('issues')))
    p.append('| First commit | %s |' % x.get('created', '—'))
    p.append('| Last push | %s |' % x.get('pushed', '—'))
    p.append('')

    p.append('## Codebase\n')
    p.append('| | |')
    p.append('|---|---|')
    p.append('| Python files | %s |' % _n(r['py_files']))
    p.append('| Lines of Python | %s |' % _n(r['loc']))
    p.append('| Tests | %s |' % _n(r['tests']))
    p.append('| Documentation pages | %s |' % _n(r['docs_pages']))
    p.append('| Commits | %s |' % _n(r['commits']))
    p.append('| Commits in the last 30 days | %s |' % _n(r['commits_30d']))
    p.append('')
    p.append('Tests run on Windows, macOS and Linux across the supported Python versions '
             'on every push — see [CI](https://github.com/%s/actions).\n' % REPO)
    p.append('*Generated %s.*\n' % now)
    return '\n'.join(p)


def write_badge(tests):
    """Point the README's test badge at the number this file just published.

    It was hand-typed, and it drifted the way a hand-kept copy always does: the
    dashboard said 1,367 while the badge said 1,706, two different definitions of
    "tests" on two surfaces, neither of them current. Counting it here is what
    makes the badge and the dashboard the same measurement. No test asserts it —
    a gate would fail every pull request that adds a test, which is why this is
    refreshed weekly by the metrics workflow instead."""
    text = _read('README.md')
    new = re.sub(r'(badge/tests-)\d+', r'\g<1>%d' % tests, text)
    if new == text:
        return
    with open(README, 'w', encoding='utf-8', newline='\n') as f:
        f.write(new)
    print('wrote', README, '(tests badge: %d)' % tests)


def main(argv):
    try:
        remote = {} if '--offline' in argv else remote_facts()
    except (urllib.error.URLError, OSError) as e:
        # Leave the committed page alone: last week's real numbers beat a page
        # of em-dashes that still looks like a successful build.
        print('metrics fetch failed (%s) — docs/dashboard.md left as it is' % e)
        return 1
    facts = repo_facts()
    text = render(facts, remote)
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)
    print('wrote', OUT)
    write_badge(facts['tests'])
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
